use QLHSUT
go

CREATE PROCEDURE sp_UV_InsertHosoUngvien
    @HOTEN NVARCHAR(100),
    @NGAYSINH DATE,
    @DIACHI NVARCHAR(100),
    @SDT NVARCHAR(20),
    @EMAIL NVARCHAR(100),
    @CCCD NVARCHAR(20),
    @NewID NVARCHAR(10) OUTPUT
AS
BEGIN
    DECLARE @LastID INT
    DECLARE @NextID NVARCHAR(10)

    SELECT TOP 1 @LastID = CAST(SUBSTRING(ID_UNGVIEN, 3, LEN(ID_UNGVIEN)) AS INT)
    FROM HOSO_UNGVIEN
    ORDER BY ID_UNGVIEN DESC

    SET @NextID = 'UV' + RIGHT('000' + CAST(@LastID + 1 AS NVARCHAR(10)), 3)

    INSERT INTO HOSO_UNGVIEN (ID_UNGVIEN, HOTEN, NGAYSINH, DIACHI, SDT, EMAIL, CCCD)
    VALUES (@NextID, @HOTEN, @NGAYSINH, @DIACHI, @SDT, @EMAIL, @CCCD)

    SET @NewID = @NextID
END
GO

CREATE PROCEDURE sp_UV_InsertUngvienChungTuBangCap
    @TEN_CHUNGTU NVARCHAR(100),
    @TEN_BANGCAP NVARCHAR(100),
    @ID_UNGVIEN VARCHAR(5),
    @ID_VITRIUNGTUYEN VARCHAR(5),
    @ID_CHUNGTU VARCHAR(5) OUTPUT,
    @ID_BANGCAP VARCHAR(5) OUTPUT
AS
BEGIN
    DECLARE @NextIDChungTu VARCHAR(5)
    DECLARE @NextIDBangCap VARCHAR(5)

    SELECT @NextIDChungTu = 'CT' + RIGHT('0000' + CAST(ISNULL(MAX(CAST(SUBSTRING(ID_CHUNGTU, 3, 3) AS INT)), 0) + 1 AS VARCHAR(3)), 3)
    FROM UNGVIEN_CHUNGTU;

    SELECT @NextIDBangCap = 'BC' + RIGHT('0000' + CAST(ISNULL(MAX(CAST(SUBSTRING(ID_BANGCAP, 3, 3) AS INT)), 0) + 1 AS VARCHAR(3)), 3)
    FROM UNGVIEN_BANGCAP;

    INSERT INTO UNGVIEN_CHUNGTU (ID_CHUNGTU, TEN_CHUNGTU, ID_UNGVIEN, ID_VITRIUNGTUYEN)
    VALUES (@NextIDChungTu, @TEN_CHUNGTU, @ID_UNGVIEN, @ID_VITRIUNGTUYEN);

    INSERT INTO UNGVIEN_BANGCAP (ID_BANGCAP, TEN_BANGCAP, ID_UNGVIEN, ID_VITRIUNGTUYEN)
    VALUES (@NextIDBangCap, @TEN_BANGCAP, @ID_UNGVIEN, @ID_VITRIUNGTUYEN);

    SET @ID_CHUNGTU = @NextIDChungTu
    SET @ID_BANGCAP = @NextIDBangCap
END;
GO

CREATE PROCEDURE sp_UV_InsertPhieuDangKiUngTuyen
    @ID_UNGVIEN VARCHAR(5),
    @ID_VITRIUNGTUYEN VARCHAR(5)
AS
BEGIN
    DECLARE @VITRI_UNGTUYEN NVARCHAR(100)

    SELECT @VITRI_UNGTUYEN = TENVITRI
    FROM VITRIUNGTUYEN
    WHERE ID_VITRIUNGTUYEN = @ID_VITRIUNGTUYEN;

    INSERT INTO PHIEUDANGKI_UNGTUYEN (ID_UNGVIEN, ID_VITRIUNGTUYEN, VITRI_UNGTUYEN)
    VALUES (@ID_UNGVIEN, @ID_VITRIUNGTUYEN, @VITRI_UNGTUYEN);
END
GO